# Linear algebra with Python and SymPy

SymPy is a Python module for performing symbolic computations. This notebook explain how use it to perform linear algebra computations.

Execute this cell to load SymPy: 

In [1]:
#load SymPy module content
from sympy import *

#this makes printouts of matrices and vectors more readeable:
init_printing(use_latex='mathjax')

## Constructions of matrices

The simplest way to create a matrix is to lists its elements. Matrices are entered row by row. Each row must be enclosed in square brackets, and then the whole collection of rows is again enclosed in square brackets: 

In [2]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
A #this displays the matrix

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

**Note.** In order to create a matrix with one row we need to enclose it entries in double square brackets (one set indicating the beginning and the end of the row, and another enclosing the whole matrix:

In [3]:
A = Matrix([[12, 13, 14]])
A

[12  13  14]

Using only one set of square brackets creates a column vector, i.e. a matrix with one column:

In [4]:
v = Matrix([12, 13, 14])
v

⎡12⎤
⎢  ⎥
⎢13⎥
⎢  ⎥
⎣14⎦

### Entering fractions

Say that we want to enter the matrix

\begin{equation*}
\begin{bmatrix}
\frac{1}{7} & -1 \\
0 & -\frac{1}{3} \\
\end{bmatrix}
\end{equation*}

We can try to do it as follows:

In [5]:
B = Matrix([[1/7 , -1],[0, -1/3]])
B

⎡0.142857142857143          -1        ⎤
⎢                                     ⎥
⎣        0          -0.333333333333333⎦

As you see fractions got converted to decimals, and rounded to some number of decimal places. For some applications in this course this would be inconvenient, since we will want to work with fractions and keep their exact values. We can deal with this issue as follows:

In [6]:
B = Matrix([[Rational(1,7) , -1],[0, Rational(-1,3)]])
B

⎡1/7   -1 ⎤
⎢         ⎥
⎣ 0   -1/3⎦

### Matrices of zeros and ones

For larger matrices it is tedious to enter all their entries manually. It is often faster to create first a  base matrix whose entries are e.g. all zeros or all ones, and then modify entries of this matrix as needed. It is easy to create such base matrices of any size:

- a zero matrix:

In [7]:
C = zeros(3, 4)  # 3 rows, 4 columns
C

⎡0  0  0  0⎤
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎣0  0  0  0⎦

- a matrix of ones:

In [8]:
D = ones(2, 7) # 2 rows, 7 columns
D

⎡1  1  1  1  1  1  1⎤
⎢                   ⎥
⎣1  1  1  1  1  1  1⎦

### Diagonal matrices

A diagonal matrix is a square matrix whose all entries outside its main diagonal are zeros. Such matrix can be created as follows: 

In [9]:
D = diag(1, 2, 3, -3)
D

⎡1  0  0  0 ⎤
⎢           ⎥
⎢0  2  0  0 ⎥
⎢           ⎥
⎢0  0  3  0 ⎥
⎢           ⎥
⎣0  0  0  -3⎦

The identity matrix is a diagonal matrix whose all entries on the main diagonal are ones. Since this matrix is used very often, there is a special way to create it:

In [10]:
I = eye(4) # 4x4 identity matrix
I

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

### Matrices from lists

In some cases it may be convenient to enter all entries of a matrix as a list, and then to reshape this list into a matrix:

In [11]:
#create a list of elements
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [12]:
#reshape the list into a 3x4 matrix
A = Matrix(a).reshape(3, 4)
A

⎡1  2   3   4 ⎤
⎢             ⎥
⎢5  6   7   8 ⎥
⎢             ⎥
⎣9  10  11  12⎦

In [13]:
#reshape the list into a 2x6 matrix
B = Matrix(a).reshape(2, 6)
B

⎡1  2  3  4   5   6 ⎤
⎢                   ⎥
⎣7  8  9  10  11  12⎦

**Note 1.** Reshaping works only if the number of elements of the list is exactly equal to the number of entries of a matrix of specified dimensions.

**Note 2.** Reshaping makes consecutive chunks of a list into rows of a matrix. In order for such chunks to become columns of a matrix, we can apply transpose of a matrix, which makes rows into columns: 

In [14]:
A

⎡1  2   3   4 ⎤
⎢             ⎥
⎢5  6   7   8 ⎥
⎢             ⎥
⎣9  10  11  12⎦

In [15]:
# B is the transpose of A, rows of A are columns of B
B = A.T 
B

⎡1  5  9 ⎤
⎢        ⎥
⎢2  6  10⎥
⎢        ⎥
⎢3  7  11⎥
⎢        ⎥
⎣4  8  12⎦

## Matrix elements, rows, and columns

Here is a sample matrix we will be working with:

In [16]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

We can access elements of a matrix by specifying the row and column of the element. 

**Note.** In Python indexing starts with 0. Thus, the first row of a matrix has index 0, the second row has index 1 and so on. 

In [17]:
A[1,0] #the element in row 1, column 0

4

We can use this to modify elements of a matrix 

In [18]:
A[1,1] = 100
A

⎡1   2   3⎤
⎢         ⎥
⎢4  100  6⎥
⎢         ⎥
⎣7   8   9⎦

Accessing matrix rows:

In [19]:
A[0, :]  # get row 0

[1  2  3]

Accessing columns:

In [20]:
A[:, 2]  # get column 2

⎡3⎤
⎢ ⎥
⎢6⎥
⎢ ⎥
⎣9⎦

We can modify the whole row (or column) of a matrix at once:

In [21]:
A

⎡1   2   3⎤
⎢         ⎥
⎢4  100  6⎥
⎢         ⎥
⎣7   8   9⎦

In [22]:
w = Matrix([[-10, -20, -30]])
w

[-10  -20  -30]

In [23]:
A[2, :] = w # make row 2 of A equal to w
A

⎡ 1    2    3 ⎤
⎢             ⎥
⎢ 4   100   6 ⎥
⎢             ⎥
⎣-10  -20  -30⎦

## Inserting and  rows and columns

Matrices can be modified by inserting into them additional rows and columns. For example, we start with the following matrix:

In [24]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

Assume the we want to insert the following column into this matrix:

In [25]:
v = Matrix([-1, -2, -3]) # matrix with one column
v

⎡-1⎤
⎢  ⎥
⎢-2⎥
⎢  ⎥
⎣-3⎦

This can be done as follows:

In [26]:
B = A.col_insert(2, v) # insert v as the column number 2
B

⎡1  2  -1  3⎤
⎢           ⎥
⎢4  5  -2  6⎥
⎢           ⎥
⎣7  8  -3  9⎦

**Note.** Column insertion creates a new matrix, the matrix `A` remains unchanged:

In [27]:
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

Row insertion works the same way:

In [28]:
C = Matrix([[100, 200, 300]]) # matrix with one row
C

[100  200  300]

In [29]:
A.row_insert(1, C) #insert C as the row number 1

⎡ 1    2    3 ⎤
⎢             ⎥
⎢100  200  300⎥
⎢             ⎥
⎢ 4    5    6 ⎥
⎢             ⎥
⎣ 7    8    9 ⎦

Row/column insertion works also with matrices consisting of more then one row or column:

In [30]:
A

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [31]:
I = eye(3)
I

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

Insert the matrix `I` into `A`, so that the first column of `I` becomes column number 3 of the new matrix:

In [32]:
B = A.col_insert(3, eye(3))
B

⎡1  2  3  1  0  0⎤
⎢                ⎥
⎢4  5  6  0  1  0⎥
⎢                ⎥
⎣7  8  9  0  0  1⎦

## Deleting rows and columns

Matrices can be also modified by deleting their rows and columns. Unlike row/column insertions, deletion modifies the original matrix: 

In [33]:
A = Matrix([[1, 2, 3], [4, 5, 6], [7,8,9], [10, 11, 12]])
A

⎡1   2   3 ⎤
⎢          ⎥
⎢4   5   6 ⎥
⎢          ⎥
⎢7   8   9 ⎥
⎢          ⎥
⎣10  11  12⎦

In [34]:
A.row_del(0) #delete row 0
A

⎡4   5   6 ⎤
⎢          ⎥
⎢7   8   9 ⎥
⎢          ⎥
⎣10  11  12⎦

In [35]:
A.col_del(1) #delete column 1
A

⎡4   6 ⎤
⎢      ⎥
⎢7   9 ⎥
⎢      ⎥
⎣10  12⎦

## Elementary row and column operations

We will work with the following matrix:

In [36]:
A = Matrix([[0 , 1, 2, 3, 4], [5, 6, 7, 8, 9], [9, 10, 11, 12, 13]])
A

⎡0  1   2   3   4 ⎤
⎢                 ⎥
⎢5  6   7   8   9 ⎥
⎢                 ⎥
⎣9  10  11  12  13⎦

We will denote by R$_i$ the row number $i$ of the matrix (remember that in Python indexing starts with 0).

Multiply  R$_1$ by $\frac{1}{5}$:

In [37]:
A[1, :] = A[1, :]*Rational(1, 5)
A

⎡0   1    2    3    4 ⎤
⎢                     ⎥
⎢1  6/5  7/5  8/5  9/5⎥
⎢                     ⎥
⎣9  10   11   12   13 ⎦

Subtract 9R$_1$ from R$_2$:

In [38]:
A[2, :] = A[2, :] - 9*A[1, :]
A

⎡0   1     2      3      4  ⎤
⎢                           ⎥
⎢1  6/5   7/5    8/5    9/5 ⎥
⎢                           ⎥
⎣0  -4/5  -8/5  -12/5  -16/5⎦

Interchange R$_0$ and R$_1$:

In [39]:
A.row_swap(0,1)
A

⎡1  6/5   7/5    8/5    9/5 ⎤
⎢                           ⎥
⎢0   1     2      3      4  ⎥
⎢                           ⎥
⎣0  -4/5  -8/5  -12/5  -16/5⎦

Elementary operations on columns can be done in the same way. For example, here we interchange column 0 and column 1:

In [40]:
A.col_swap(0,1)
A

⎡6/5   1  7/5    8/5    9/5 ⎤
⎢                           ⎥
⎢ 1    0   2      3      4  ⎥
⎢                           ⎥
⎣-4/5  0  -8/5  -12/5  -16/5⎦

## Row reduction

In [41]:
A = Matrix([[1, 2, 3, 12], [4, 5, 6, 13], [7,8,9, 14]])
A

⎡1  2  3  12⎤
⎢           ⎥
⎢4  5  6  13⎥
⎢           ⎥
⎣7  8  9  14⎦

The function `rref()` computes the row reduced echelon form of a matrix:

In [42]:
R = A.rref()
R

⎛⎡1  0  -1  -34/3⎤        ⎞
⎜⎢               ⎥        ⎟
⎜⎢0  1  2   35/3 ⎥, (0, 1)⎟
⎜⎢               ⎥        ⎟
⎝⎣0  0  0     0  ⎦        ⎠

**Note.** `A.rref()` returns a tuple consisting of a reduced matrix and a list of indices of pivot columns. To get the reduced matrix only we need to select the first entry of this tuple:

In [43]:
B = A.rref()[0]
B

⎡1  0  -1  -34/3⎤
⎢               ⎥
⎢0  1  2   35/3 ⎥
⎢               ⎥
⎣0  0  0     0  ⎦

### Errors in row reduction with decimals

Here is an example showing that row reduction of matrices with decimal entries can give wrong results:

In [44]:
A = Matrix([[1, 3],[0.1, 0.3]])
A

⎡ 1    3 ⎤
⎢        ⎥
⎣0.1  0.3⎦

In [45]:
A.rref() # the result is wrong!

⎛⎡1  0⎤        ⎞
⎜⎢    ⎥, (0, 1)⎟
⎝⎣0  1⎦        ⎠

Such issues occur because computer operations on numbers in the decimal form involve rounding errors, and this distorts the end result. 

We can avoid such problems by entering all entries of a matrix as rational numbers:

In [46]:
A = Matrix([[1, 3],[Rational(1,10), Rational(3,10)]])
A

⎡ 1     3  ⎤
⎢          ⎥
⎣1/10  3/10⎦

Now the reduced echelon form is computed correctly:

In [47]:
A.rref()

⎛⎡1  3⎤      ⎞
⎜⎢    ⎥, (0,)⎟
⎝⎣0  0⎦      ⎠

## Matrix algebra

We will be working with the following matrices `A` and `B`:

In [48]:
A = Matrix([[0, 1], [2, 3], [4,5]])
A

⎡0  1⎤
⎢    ⎥
⎢2  3⎥
⎢    ⎥
⎣4  5⎦

In [49]:
B = Matrix([[3, 2], [1, 0], [-1,2]])
B

⎡3   2⎤
⎢     ⎥
⎢1   0⎥
⎢     ⎥
⎣-1  2⎦

**Addition of matrices:**

In [50]:
A+B

⎡3  3⎤
⎢    ⎥
⎢3  3⎥
⎢    ⎥
⎣3  7⎦

**Multiplication of a matrix by a scalar:**

In [51]:
Rational(1, 2)*A

⎡0  1/2⎤
⎢      ⎥
⎢1  3/2⎥
⎢      ⎥
⎣2  5/2⎦

**Transpose of a matrix:**

In [52]:
A.T

⎡0  2  4⎤
⎢       ⎥
⎣1  3  5⎦

**Matrix multiplication:**

In [53]:
C = (A.T)*B
C

⎡-2  8 ⎤
⎢      ⎥
⎣1   12⎦

We can multiply a matrix by a column vector in the same way:

In [54]:
A

⎡0  1⎤
⎢    ⎥
⎢2  3⎥
⎢    ⎥
⎣4  5⎦

In [55]:
v = Matrix([-1, 2])
v

⎡-1⎤
⎢  ⎥
⎣2 ⎦

In [56]:
A*v

⎡2⎤
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣6⎦

**Matrix inverse:**

In [57]:
C.inv()

⎡-3/8  1/4 ⎤
⎢          ⎥
⎣1/32  1/16⎦

Not every matrix is invertible. An attempt to compute an inverse of a non-invertible matrix will give an error:

In [58]:
# this matrix is non-invertible
A = Matrix([[1, 0], [1, 0]])
A

⎡1  0⎤
⎢    ⎥
⎣1  0⎦

In [59]:
A.inv()

NonInvertibleMatrixError: Matrix det == 0; not invertible.

**Matrix powers:**

Taking the $n$-th power of a matrix has the same effect as multiplying the matrix by itself $n$ times.

In [60]:
A = Matrix([[1, 2], [3, 4]])

Multiplying the matrix by itself 4 times:

In [61]:
A*A*A*A

⎡199  290⎤
⎢        ⎥
⎣435  634⎦

Taking the 4-th power of $A$:

In [62]:
A**4

⎡199  290⎤
⎢        ⎥
⎣435  634⎦

## Determinant

In [63]:
A = Matrix([[1, 1, 2], [3, 4, 5], [6,7,8]])
A

⎡1  1  2⎤
⎢       ⎥
⎢3  4  5⎥
⎢       ⎥
⎣6  7  8⎦

Compute the determinant of the matrix `A`:

In [64]:
A.det()

-3

## Row space, column space, and null space

In [65]:
A = Matrix([[1, 2, 3, 4],[5, 6, 7, 8], [4, 4, 4, 4]])
A

⎡1  2  3  4⎤
⎢          ⎥
⎢5  6  7  8⎥
⎢          ⎥
⎣4  4  4  4⎦

A basis of the row space:

In [66]:
A.rowspace()

[[1  2  3  4], [0  -4  -8  -12]]

A basis of the column space:

In [67]:
A.columnspace()

⎡⎡1⎤  ⎡2⎤⎤
⎢⎢ ⎥  ⎢ ⎥⎥
⎢⎢5⎥, ⎢6⎥⎥
⎢⎢ ⎥  ⎢ ⎥⎥
⎣⎣4⎦  ⎣4⎦⎦

A basis of the null space:

In [68]:
A.nullspace()

⎡⎡1 ⎤  ⎡2 ⎤⎤
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢-2⎥  ⎢-3⎥⎥
⎢⎢  ⎥, ⎢  ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎣⎣0 ⎦  ⎣1 ⎦⎦

## Dot product and Gram-Schmidt process

We define a few column vectors:

In [69]:
u = Matrix([1, 1, 1])
v = Matrix([1, 2, 3])
w = Matrix([1, -1, 0])
u, v, w

⎛⎡1⎤  ⎡1⎤  ⎡1 ⎤⎞
⎜⎢ ⎥  ⎢ ⎥  ⎢  ⎥⎟
⎜⎢1⎥, ⎢2⎥, ⎢-1⎥⎟
⎜⎢ ⎥  ⎢ ⎥  ⎢  ⎥⎟
⎝⎣1⎦  ⎣3⎦  ⎣0 ⎦⎠

Dot product of vectors `v` and `w`:

In [70]:
v.dot(w)

-1

Gram-Schmidt orthogonalization of the set of vectors $[$ `u`, `v`, `w` $]$:

In [71]:
GramSchmidt([u, v, w])

⎡⎡1⎤  ⎡-1⎤  ⎡1/2⎤⎤
⎢⎢ ⎥  ⎢  ⎥  ⎢   ⎥⎥
⎢⎢1⎥, ⎢0 ⎥, ⎢-1 ⎥⎥
⎢⎢ ⎥  ⎢  ⎥  ⎢   ⎥⎥
⎣⎣1⎦  ⎣1 ⎦  ⎣1/2⎦⎦

Adding the option `orthonormal=True` we obtain a set of orthonormal vectors:

In [72]:
GramSchmidt([u, v, w], orthonormal=True)

⎡⎡√3⎤          ⎡ √6 ⎤⎤
⎢⎢──⎥  ⎡-√2 ⎤  ⎢ ── ⎥⎥
⎢⎢3 ⎥  ⎢────⎥  ⎢ 6  ⎥⎥
⎢⎢  ⎥  ⎢ 2  ⎥  ⎢    ⎥⎥
⎢⎢√3⎥  ⎢    ⎥  ⎢-√6 ⎥⎥
⎢⎢──⎥, ⎢ 0  ⎥, ⎢────⎥⎥
⎢⎢3 ⎥  ⎢    ⎥  ⎢ 3  ⎥⎥
⎢⎢  ⎥  ⎢ √2 ⎥  ⎢    ⎥⎥
⎢⎢√3⎥  ⎢ ── ⎥  ⎢ √6 ⎥⎥
⎢⎢──⎥  ⎣ 2  ⎦  ⎢ ── ⎥⎥
⎣⎣3 ⎦          ⎣ 6  ⎦⎦

## Eigenvalues, eigenvectors, diagonalization

### Characteristic polynomial

In [73]:
A = Matrix([[3, -2,  4, -2], [5,  3, -3, -2], [5, -2,  2, -2], [5, -2, -3,  3]])
A

⎡3  -2  4   -2⎤
⎢             ⎥
⎢5  3   -3  -2⎥
⎢             ⎥
⎢5  -2  2   -2⎥
⎢             ⎥
⎣5  -2  -3  3 ⎦

In [74]:
# declare a variable lamda (this is not a misspeling, 
#"lambda" already has a different meaning in Python)
lamda = symbols('lamda') 

# compute the characteristic polynomial of matrix A with lamda as the variable
p = A.charpoly(lamda)
p

PurePoly(lamda**4 - 11*lamda**3 + 29*lamda**2 + 35*lamda - 150, lamda, domain=
'ZZ')

Factorization of the polynomial:

In [75]:
factor(p)

PurePoly(lamda**4 - 11*lamda**3 + 29*lamda**2 + 35*lamda - 150, lamda, domain=
'ZZ')

### Eigenvalues and eigenvectors

Eigenvalues of the matrix `A` with their algebraic multiplicities:

In [76]:
A.eigenvals()

{-2: 1, 3: 1, 5: 2}

Eigenvalues with their  algebraic multiplicities and bases of eigenspaces:

In [77]:
A.eigenvects()

⎡⎛       ⎡⎡0⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞  ⎛      ⎡⎡1⎤  ⎡0 ⎤⎤⎞⎤
⎢⎜       ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎢⎜       ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥  ⎢-1⎥⎥⎟⎥
⎢⎜-2, 1, ⎢⎢ ⎥⎥⎟, ⎜3, 1, ⎢⎢ ⎥⎥⎟, ⎜5, 2, ⎢⎢ ⎥, ⎢  ⎥⎥⎟⎥
⎢⎜       ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥  ⎢0 ⎥⎥⎟⎥
⎢⎜       ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎣⎝       ⎣⎣1⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠  ⎝      ⎣⎣0⎦  ⎣1 ⎦⎦⎠⎦

### Diagonalization of matrices

Diagonalization of a matrix (returns a tuple consistsing of matrices $P$ and $D$ such that $A = PDP^{-1}$):

In [78]:
A.diagonalize()

⎛⎡0  1  1  0 ⎤  ⎡-2  0  0  0⎤⎞
⎜⎢           ⎥  ⎢           ⎥⎟
⎜⎢1  1  1  -1⎥  ⎢0   3  0  0⎥⎟
⎜⎢           ⎥, ⎢           ⎥⎟
⎜⎢1  1  1  0 ⎥  ⎢0   0  5  0⎥⎟
⎜⎢           ⎥  ⎢           ⎥⎟
⎝⎣1  1  0  1 ⎦  ⎣0   0  0  5⎦⎠

Complex diagonalization:

In [79]:
B = Matrix([[0, 1],[-1, 0]])
B

⎡0   1⎤
⎢     ⎥
⎣-1  0⎦

In [80]:
B.diagonalize()

⎛⎡ⅈ  -ⅈ⎤  ⎡-ⅈ  0⎤⎞
⎜⎢     ⎥, ⎢     ⎥⎟
⎝⎣1  1 ⎦  ⎣0   ⅈ⎦⎠

Not every matrix is diagonalizable. For such matrices we will get an error:

In [81]:
# this matrix is not diagonalizable
C = Matrix([[2, 1], [0, 2]])
C

⎡2  1⎤
⎢    ⎥
⎣0  2⎦

In [82]:
C.diagonalize()

MatrixError: Matrix is not diagonalizable

## Singular Value Decomposition

In [83]:
A = Matrix([[0, 1, 2, 3], [4, 6, 7, 0], [1, 1, 0, 0]])
A

⎡0  1  2  3⎤
⎢          ⎥
⎢4  6  7  0⎥
⎢          ⎥
⎣1  1  0  0⎦

`sympy` does not include a function for computing singular value decomposition, but such function can be imported from from `mpmath`:

In [84]:
from mpmath import svd

In [85]:
U, S, V = svd(A)

`U` and `V` are orthogonal matrices, `S` is the vector of singular values:

In [86]:
U

⎡-0.211721215903945   -0.971337526391343  0.108062651087702 ⎤
⎢                                                           ⎥
⎢-0.972676773708509   0.198644273600799   -0.120167992633721⎥
⎢                                                           ⎥
⎣-0.0952576538875581  0.130552144331522   0.986854658491451 ⎦

In [87]:
S

matrix(
[['10.3117751931661'],
 ['3.12657593986521'],
 ['0.944359707876459']])

In [88]:
V

matrix(
[['-0.386544961857121', '-0.595730550459802', '-0.701351582272704', '-0.0615959556733527'],
 ['0.295892137766083', '0.112289055598665', '-0.176603782603437', '-0.932014009965052'],
 ['0.536006231242966', '0.395939545766543', '-0.661877715712972', '0.34328863309098']])

`S` and `V` are not displayed nicely since they are `mpmath` matrices, and not `sympy` matrices. This can be fixed as follows:

In [89]:
import numpy as np
V = Matrix(np.array(V.tolist(),dtype=np.float64))
V

⎡-0.386544961857121  -0.595730550459802  -0.701351582272704  -0.06159595567335
⎢                                                                             
⎢0.295892137766083   0.112289055598665   -0.176603782603437  -0.93201400996505
⎢                                                                             
⎣0.536006231242966   0.395939545766543   -0.661877715712972   0.34328863309098

27⎤
  ⎥
2 ⎥
  ⎥
  ⎦

In [90]:
S = diag(*[Float(x) for x in S])
S

⎡10.3117751931661         0                  0        ⎤
⎢                                                     ⎥
⎢       0          3.12657593986521          0        ⎥
⎢                                                     ⎥
⎣       0                 0          0.944359707876459⎦